# .github/workflows/ci.yml

name: CI

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

      - name: Install dependencies and your package
        run: |
          poetry install
          poetry build
          # Install the package itself; adjust if your package has specific installation needs
          poetry run pip install dist/*.whl

      - name: Run Python tests
        run: simulatorwizard

